rewrite ^/$ /index.html last;
access_log /var/log/nginx/timings.log timings;

location ~ ^/index\.(.*\.)?html$ {
    alias __INSTALL_DIR__/www/;
    try_files $uri index.$landingpage_lang.html index.en.html;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}

location ~ ^/donate\.(.*\.)?html$ {
    alias __INSTALL_DIR__/www/;
    try_files $uri donate.$landingpage_lang.html donate.en.html;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    # auth_basic           "Not public yet!";
    # auth_basic_user_file __INSTALL_DIR__/.htpasswd;
}

location ~ ^/roadmap\.(.*\.)?html$ {
    alias __INSTALL_DIR__/www/;
    try_files $uri roadmap.$landingpage_lang.html roadmap.en.html;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    # auth_basic           "Not public yet!";
    # auth_basic_user_file __INSTALL_DIR__/.htpasswd;
}

location ~ ^/assets/ {
    alias __INSTALL_DIR__/www/;
    try_files $uri $uri;
    more_set_headers "Cache-Control: public, max-age=300";
    expires 30d;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}

location = /favicon.ico {
    return 302 assets/img/ynh_logo_roundcorner.png;
    log_not_found off;
    access_log off;
}

location = /robots.txt {
    allow all;
    log_not_found off;
    access_log off;
}

location = /github {
    proxy_pass http://127.0.0.1:__PORT__/hooks/github;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
