#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

# User creates www-data directory
usermod -a -G www-data "$app"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

chown "$app:www-data" "$install_dir"
mkdir -p "$install_dir/www"

ynh_config_add --template="webhook.yml" --destination="$install_dir/webhook.yml"
ynh_config_add --template="webhook.sh" --destination="$install_dir/webhook.sh"
chmod +x "$install_dir/webhook.sh"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

LANGS="$(curl -s https://translate.yunohost.org/api/components/yunohost/landingpage/statistics/ \
    | jq -r '.results[] | select(.translated_percent > 50) | .code' | grep -v "^en$")"

ynh_config_add --template="nginx_lang_map.conf" --destination="$lang_map_conf" --jinja
chown root: "$lang_map_conf"
chmod 644 "$lang_map_conf"

ynh_config_add_systemd --service="$app-webhook" --template="webhook.service"
yunohost service add "$app" --description="$app update webhook" --log="/var/log/$app/$app-webhook.log"

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-webhook" --action="start"

#=================================================
# END OF SCRIPT
#=================================================
ynh_print_warn "Now, please write your Github Personal Access token in $install_dir/github_token so that the webhook can download artifacts!"

ynh_script_progression "Installation of $app completed"
