#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

_git_clone_or_pull "$install_dir/landingpage"

mkdir -p "$install_dir/www"
chown -R "$app:www-data" "$install_dir/www"
chmod g+s "$install_dir/www"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing app..."

pushd "$install_dir" > /dev/null

_update_venv
ynh_exec_as_app "$install_dir/venv/bin/pip" install -r landingpage/requirements.txt > /dev/null

ynh_exec_as_app LANDINGPAGE_DIST_DIR="$install_dir/www" ./landingpage/bin/regenerate.sh

popd > /dev/null

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
