#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

# User creates www-data directory
usermod -a -G www-data "$app"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

chown "$app:www-data" "$install_dir"
_git_clone_or_pull "$install_dir/landingpage"
mkdir -p "$install_dir/www"

: "${uptime_kuma_id:=}"
ynh_config_add --template="service_notify_kuma.sh" --destination="$install_dir/service_notify_kuma.sh"
chmod +x "$install_dir/service_notify_kuma.sh"

ynh_config_add --template="update.sh" --destination="$install_dir/update.sh"
chmod +x "$install_dir/update.sh"

chown -R "$app:$app" "$install_dir/landingpage"
chown -R "$app:www-data" "$install_dir/www"
chmod g+s "$install_dir/www"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing app..."

pushd "$install_dir"
	_update_venv
	ynh_exec_as_app "$install_dir/venv/bin/pip" install -r landingpage/requirements.txt > /dev/null
	ynh_exec_as_app LANDINGPAGE_DIST_DIR="$install_dir/www" ./landingpage/bin/regenerate.sh
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

LANGS="$(curl -s https://translate.yunohost.org/api/components/yunohost/landingpage/statistics/ \
    | jq -r '.results[] | select(.translated_percent > 50) | .code' | grep -v "^en$")"

ynh_config_add --template="nginx_lang_map.conf" --destination="$lang_map_conf" --jinja
chown root: "$lang_map_conf"
chmod 644 "$lang_map_conf"

ynh_config_add --template="systemd-update.service" --destination="/etc/systemd/system/$app-update.service"
ynh_config_add --template="systemd-update.timer" --destination="/etc/systemd/system/$app-update.timer"
systemctl daemon-reload
systemctl enable "$app-update.timer" --now --quiet

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
