#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

# User creates www-data directory
usermod -a -G www-data "$app"


#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's webhook systemd service..."

ynh_systemctl --service="$app-webhook" --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# Remove legacy stuff
ynh_safe_rm "$install_dir/service_notify_kuma.sh"
ynh_safe_rm "$install_dir/update.sh"
ynh_config_remove_systemd systemd-update.timer
ynh_config_remove_systemd systemd-update.service
systemctl daemon-reload

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

chown "$app:www-data" "$install_dir"
mkdir -p "$install_dir/www"

ynh_config_add --template="webhook.yml" --destination="$install_dir/webhook.yml"
ynh_config_add --template="webhook.sh" --destination="$install_dir/webhook.sh"
chmod +x "$install_dir/webhook.sh"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

LANGS="$(curl -s https://translate.yunohost.org/api/components/yunohost/landingpage/statistics/ \
    | jq -r '.results[] | select(.translated_percent > 50) | .code' | grep -v "^en$")"

ynh_config_add --template="nginx_lang_map.conf" --destination="$lang_map_conf" --jinja
chown root: "$lang_map_conf"
chmod 644 "$lang_map_conf"

ynh_config_add_systemd --service="$app-webhook" --template="webhook.service"
yunohost service add "$app" --description="$app update webhook" --log="/var/log/$app/$app-webhook.log"

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-webhook" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
