#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

chown "$app:www-data" "$install_dir"
_git_clone_or_pull "$install_dir/landingpage"
mkdir -p "$install_dir/www"

ynh_config_add --template="service_notify_kuma.sh" --destination="$install_dir/service_notify_kuma.sh"
chmod +x "$install_dir/service_notify_kuma.sh"

chown -R "$app:$app" "$install_dir/landingpage"
chown -R "$app:www-data" "$install_dir/www"
chmod g+s "$install_dir/www"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Upgrading app..." --weight=5

pushd "$install_dir"
	_update_venv
	ynh_exec_as_app "$install_dir/venv/bin/pip" install -r landingpage/requirements.txt > /dev/null
	ynh_exec_as_app LANDINGPAGE_DIST_DIR="$install_dir/www" ./landingpage/bin/regenerate.sh
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add --template="nginx_lang_map.conf" --destination="$lang_map_conf"
chown root: "$lang_map_conf"
chmod 644 "$lang_map_conf"

ynh_config_add --template="systemd-update.service" --destination="/etc/systemd/system/$app-update.service"
ynh_config_add --template="systemd-update.timer" --destination="/etc/systemd/system/$app-update.timer"
systemctl daemon-reload
systemctl enable "$app-update.timer" --now --quiet

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
